### ISSUE TITLE
Add vignette docs for complete_dates function

### ISSUE THREAD

**Issue by TimTaylor** [reconverse/incidence2#59]

**Comment by tjtnew** [comment]
Still need to add example to vignette but function is at least now mentioned (https://github.com/reconverse/incidence2/commit/5ab71af0b10a45fdcb6140028bada4d681cb2356)

**Comment by TimTaylor** [comment]
Function renamed and updated via https://github.com/reconverse/incidence2/commit/1ef0420a031462eb252d69046fd6fc8f8f1b6c82

**Comment by TimTaylor** [comment]
closed by https://github.com/reconverse/incidence2/commit/085a715100fb1d37a821948061660b4988cdfacf
