### ISSUE TITLE
Feedback wanted: considering removing support for NSE in inputs

### ISSUE THREAD

**Issue by TimTaylor** [reconverse/incidence2#78]
Currently we support both quoted and unquoted inputs to the incidence function making use of {rlang} and {tidyeval} to do so. Whilst on first glance this is appealing it does complicate the code base making it more complicated to maintain and increases the chance of introducing a subtle bug. I'd be inclined to remove this feature but wanted to get some feedback first. @thibautjombart  - any thoughts?

**Comment by thibautjombart** [comment]
I think this is an important discussion with likely wider application to the rest of the reconverse. I would lean towards removal, but this should be a wider consultation, as we don't want to rush this and then revert the decision :) Do you have a preferred timeline for resolving this?

**Comment by TimTaylor** [comment]
Support removed by https://github.com/reconverse/incidence2/commit/1ef0420a031462eb252d69046fd6fc8f8f1b6c82
